name: Publish package on release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up 'publish.properties'
        run: |
          echo "${{ secrets.SIGNING_KEY_FILE }}" > signingKey.asc
          echo "${{ secrets.PUBLISH_PROPERTIES }}" > publish.properties

      - name: Build and test
        if: success()
        run: ./gradlew build

      - name: Publish to GitHub packages
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish

      - name: Publish and release on Maven
        if: success()
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
